# Pytorch Grundlagen

dieses Notebook basiert auf der Arbeit von: Dilara Soylu (Stanford), Phillip Lippe (U. Amsterdam), David Bau (MIT) & Pytorch.Org Tutorial Contributers; überarbeitet von Mohammed Al-Jaff (Uppsala University)

mit eigenen Beispielen, Überarbeitungen und Übersetzungen von: Marc Benesch


## Was ist Pytorch?
- Alternative zu numpy, mit GPU-Beschleunigung verfügbar
- Python-Bibliothek für Auto-Differentation insbesondere für Neural Networks

Pytorch wurde und wird von Facebook (Meta) entwickelt und stellt eine Alternative zu Tensorflow dar. Obwohl Tensorflow (von Google entwickelt) weitaus populärer ist, scheint sich Pytorch vor allem in den letzten Jahren stärker zu etablieren. Vor allem im wissenschaftlichen Umfeld wird fast ausschließlich Pytorch verwendet. Beide Frameworks sind jedoch sehr ähnlich und vor allem für Anfänger ist kaum ein Unterschied erkennbar.\
Pytorch hat ebenso viele Ähnlichkeiten zu numpy. Wer sich mit numpy gut auskennt, wird Pytorch schnell verstehen. Beispielweise ist `torch.Tensor` das Äquivalent zu numpy's `numpy.ndarray`. Mit den Funktionen `a.numpy()` und `torch.from_numpy(b)` lassen sich numpy arrays und torch tensors leicht ineinander umwandeln.\
Beginnen wir mit den Imports:

In [1]:
import torch
import numpy as np


print(f"Version: {torch.__version__}")

Version: 2.2.1+cu121


## Torch Tensor

[Tensor](https://de.wikipedia.org/wiki/Tensor) ist eine Bezeichnung aus der linearen Algebra. Was genau das bedeutet, soll uns zunächst nicht interessieren. Wichtig ist: ein Vektor ist ein 1-D Tensor und eine Matrix ist ein 2-D Tensor. Wie in numpy kann man einen Tensor mit beliebigen Dimensionen haben. Diese werden wir vor allem bei NNs brauchen. Viele Funktionen, die du evtl. aus numpy scon kennst, funktionieren auch bei Tensoren.

In [2]:
# Python Liste zu Tensor
x = [3, 7, 1, 4]
my_tensor = torch.tensor(x)

print(my_tensor)

tensor([3, 7, 1, 4])


In [3]:
# Python 2D Liste zu Tensor
x = [
      [2, 6],
      [9, 4],
      [0, 3]
]
my_2D_tensor = torch.tensor(x)

print(my_2D_tensor)

tensor([[2, 6],
        [9, 4],
        [0, 3]])


Wir können einen Tensor auch direkt mit vordefiniertem Inhalt bestimmen. Die wichtigsten Funktionen sind:
- `torch.zeros`: erstellt einen Tensor mit Nullen
- `torch.ones`: erstellt einen Tensor mit Einsen
- `torch.rand`: erstellt einen Tensor mit Zufallszahlen von 0 bis 1 (gleichförmige Verteilung)
- `torch.randn`: erstellt einen Tensor mit Zufallszahlen einer Normalverteilung mit Mittelwert 0 und Varianz 1
- `torch.arange`: wie numpy's arange, siehe [hier](https://pytorch.org/docs/stable/generated/torch.arange.html)
- `torch.linspace`: wie numpy's linspace, siehe [hier](https://pytorch.org/docs/stable/generated/torch.linspace.html)

In [4]:
zeros = torch.zeros(4)
print(zeros)

ones = torch.ones((2, 3)) # man kann die Dimensionen des tensors angeben, hier: 2x3
print(ones)

x1 = torch.arange(1, 3, 0.5) # von 1 bis 3 (exklusiv) in 0.5er Schritten
print(x1)
x2 = torch.linspace(1, 3, 5) # 5 samples von 1 bis 3 (inklusiv) mit gleichem Abstand
print(x2)

tensor([0., 0., 0., 0.])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([1.0000, 1.5000, 2.0000, 2.5000])
tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000])


Wir können außerdem Tensoren aus anderen Tensoren erstellen:
- `torch.ones_like(old_tensor)`: erstellt einen Tensor mit den Dimensionen von `old_tensor` gefüllt mit Einsen
- `torch.zeros_like(old_tensor`: gleiches Prinzip mit Nullen
- `torch.rand_like(old_tensor)`: gleiches Prinzip mit Zufallszahlen zwischen 0 und 1 (siehe oben)
- `torch.randn_like(old_tensor)`: gleiches Prinzip mit Zufallszahlen einer Normalverteilung (siehe oben)\

Das ist vor allem nützlich, wenn wir uns über die Dimensionen (shape) eines Tensors keine Gedanken machen wollen.

In [5]:
rand_tensor = torch.rand_like(ones) # keine Ahnung, was 'ones' für Dimensionen hat
print(rand_tensor)

tensor([[0.5460, 0.9804, 0.6334],
        [0.8855, 0.2844, 0.1945]])


## Numpy to Torch und andersrum

In [6]:
# Python list
x = [
     [4, 1, 9],
     [5, 3, 6],
     [0, 7, 2]
]

# zu numpy
x_np = np.array(x)

# zu torch tensor
x_tensor = torch.from_numpy(x_np)

print(x_tensor)

tensor([[4, 1, 9],
        [5, 3, 6],
        [0, 7, 2]])


In [7]:
# andersrum
x_tensor = torch.arange(5)
x_np = x_tensor.numpy()

print(x_np)
print(type(x_np))

[0 1 2 3 4]
<class 'numpy.ndarray'>


## `.shape` und `.dtype`

Wie in numpy gibt es die Attribute Shape (gibt die Dimensionen des Tensors zurück) und Dtype (gibt den Datentypen des Tensors zurück).

In [8]:
x = torch.randn(3, 2, 2)

print(x.shape)
print(x.dtype)

torch.Size([3, 2, 2])
torch.float32


In [9]:
# oder in genau einer Dimension
print(x.shape[0])

3


Wir können beim Erstellen des Tensors auch direkt einen Datentypen angeben.

In [10]:
x = [
      [2, 6],
      [9, 4],
      [0, 3]
]

x_tensor = torch.tensor(x, dtype=torch.float)
print(x_tensor)

tensor([[2., 6.],
        [9., 4.],
        [0., 3.]])


In [11]:
# mit bool bekommen wir entweder True (wenn die Zahl nicht 0 ist) oder
# False (wenn die Zahl 0 ist)
x_tensor_bools = torch.tensor(x, dtype=torch.bool)
print(x_tensor_bools)

tensor([[ True,  True],
        [ True,  True],
        [False,  True]])


## Ändern der Dimension eines Tensors (`shape`)

Dazu gibt es zwei Wege: `.reshape()` oder `.view()`

In [12]:
# 5x4 Tensor erstellen
x = torch.rand(5, 4)

x_view = x.view(2, 10)
print(x_view)

# x und x_view teilen den selben Speicherplatz, d.h. wenn ich einen ändere
# ändert sich der andere mit
x_view[0][0] = 9999

print(x)

tensor([[0.0161, 0.0848, 0.1405, 0.0890, 0.4075, 0.3470, 0.1150, 0.7130, 0.5896,
         0.5216],
        [0.4769, 0.4725, 0.8485, 0.8266, 0.1862, 0.8596, 0.5141, 0.6714, 0.5994,
         0.6152]])
tensor([[9.9990e+03, 8.4797e-02, 1.4054e-01, 8.9032e-02],
        [4.0750e-01, 3.4697e-01, 1.1505e-01, 7.1299e-01],
        [5.8962e-01, 5.2156e-01, 4.7688e-01, 4.7250e-01],
        [8.4850e-01, 8.2664e-01, 1.8618e-01, 8.5960e-01],
        [5.1405e-01, 6.7137e-01, 5.9937e-01, 6.1521e-01]])


In [13]:
x = torch.zeros(2, 4)
print(f"Original x: {x}")

# reshape benutzen, um aus 2x4 einen 8x1 Vektor zu machen
x = x.reshape((8, 1))
print(f"Reshaped x: {x}")

Original x: tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Reshaped x: tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])


Das ist sehr nützlich, wenn wir mit Bildern in NNs arbeiten.

In [14]:
x = torch.arange(6)
print(f"arange: {x}")

x = x.reshape(2, 3)
print(f"reshape: {x}")

x = x.permute(1, 0) # tausche Achsen 1 und 0 (Spalten werden zu Zeilen und anderherum)
print(f"permute: {x}")

arange: tensor([0, 1, 2, 3, 4, 5])
reshape: tensor([[0, 1, 2],
        [3, 4, 5]])
permute: tensor([[0, 3],
        [1, 4],
        [2, 5]])


## Slicing und Indexing

In [15]:
print(x[0,:]) # erste Reihe komplett wiedergeben
print(x[:, 0]) # erste Spalte komplett wiedergeben

print(x[1:, 1]) # zweite Spalte ab dem ersten Element wiedergeben
print(x[1:3, :]) # gibt die zweite und dritte Zeile komplett wieder

tensor([0, 3])
tensor([0, 1, 2])
tensor([4, 5])
tensor([[1, 4],
        [2, 5]])


## Operationen auf Tensoren

Viele Operationen aus numpy sind auch in Pytorch verfügbar. Eine vollständige Liste kann [hier](https://pytorch.org/docs/stable/tensors.html#%7D) gefunden werden.

In [16]:
# skalare Operationen
x1 = torch.arange(9, dtype=torch.float).reshape(3, 3)
x2 = torch.rand((3, 3))

print(f"Addition: {x1 + x2}")
print(f"Elementweise Multiplikation: {x1 * 2}")

Addition: tensor([[0.6634, 1.9623, 2.0334],
        [3.3045, 4.6035, 5.0027],
        [6.8948, 7.8512, 8.9316]])
Elementweise Multiplikation: tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.],
        [12., 14., 16.]])


In [17]:
# Matrix-Multiplikation wie in numpy mit '@'
print(x1 @ x2)

tensor([[ 2.0941,  2.3060,  1.8659],
        [ 7.6820,  9.5570,  4.7689],
        [13.2700, 16.8081,  7.6719]])


In [19]:
# lineare Algebra spezifische Berechnungen
print(torch.inverse(x2)) # berechnet Inverse
print(torch.linalg.eig(x2)) # berechnet die Eigenwerte

tensor([[ 6.1289, -9.5015, -0.1922],
        [-3.0793,  6.4375,  0.0918],
        [-3.0727,  3.2434,  1.1741]])
torch.return_types.linalg_eig(
eigenvalues=tensor([0.0849+0.j, 1.2590+0.j, 0.8546+0.j]),
eigenvectors=tensor([[ 0.8002+0.j, -0.2418+0.j, -0.0446+0.j],
        [-0.4680+0.j, -0.1163+0.j, -0.0435+0.j],
        [-0.3751+0.j, -0.9633+0.j,  0.9981+0.j]]))
